# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "PaperModest"
license = "MIT"
licenselink = "https://github.com/faisaldarbar/hugo-PaperModest/blob/master/LICENSE"
description = "A customized fork of PaperMod for my personal site. Shared for others, but not actively maintained."
homepage = "https://github.com/faisaldarbar/hugo-PaperModest"
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist",
  "highlight.js",
  "search"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
min_version = "0.146.0"

[author]
  name = "Faisal Darbar"
  homepage = "https://github.com/faisaldarbar/"

# If porting an existing theme
[original]
  name = "PaperMod"
  author = "adityatelange"
  homepage = "https://github.com/adityatelange"
  repo = "https://github.com/adityatelange/hugo-papermod/"
